---
depends_on: null
kind: pipeline
type: kubernetes
name: build-educators-staging

resources:
  requests:
    cpu: 8
    memory: 4GiB

steps:
  - name: publish-staging
    image: plugins/kaniko-ecr
    environment:
      NPM_AUTH:
        from_secret: NPM_AUTH
      NPM_EMAIL:
        from_secret: NPM_EMAIL
      CMS_URL:
        from_secret: CMS_URL_STAGING
      CMS_API_KEY:
        from_secret: CMS_API_KEY
    settings:
      create_repository: true
      cache_from: latest-staging
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: devrel/${DRONE_REPO_NAME}
      build_args:
        - NPM_AUTH
        - NPM_EMAIL
        - CMS_URL
        - CMS_API_KEY
      tags:
        - educators-staging-build-${DRONE_BUILD_NUMBER}
        - latest-staging
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key

  - name: deploy-staging
    image: drone/cli:1.4.0-alpine
    commands:
      - drone build promote mongodb/educators ${DRONE_BUILD_NUMBER} staging
    environment:
      DRONE_SERVER: ${DRONE_SYSTEM_PROTO}://${DRONE_SYSTEM_HOST}
      DRONE_TOKEN:
        from_secret: drone_token

trigger:
  branch:
    - test-docker-cache
  event:
    - push
  action:
    exclude:
      - synchronized

---
depends_on: null
kind: pipeline
type: kubernetes
name: deploy-educators-staging

steps:
  - name: deploy-staging
    image: quay.io/mongodb/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.7.3
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: devrel
      release: educators
      values: image.tag=educators-staging-build-${DRONE_BUILD_PARENT},image.pullPolicy=Always,image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/devrel/${DRONE_REPO_NAME}
      api_server: https://api.staging.corp.mongodb.com
      kubernetes_token:
        from_secret: staging_kubernetes_token
      values_files: ['environments/staging.yaml']

trigger:
  event:
    - promote
    - rollback
  target:
    - staging

---
depends_on: null
kind: pipeline
type: kubernetes
name: build-educators-prod

resources:
  requests:
    cpu: 8
    memory: 4GiB

steps:
  - name: publish-production
    image: plugins/kaniko-ecr
    environment:
      NPM_AUTH:
        from_secret: NPM_AUTH
      NPM_EMAIL:
        from_secret: NPM_EMAIL
      CMS_URL:
        from_secret: CMS_URL_STAGING # This should be changed when we get the CMS API on Kanpoy.
      CMS_API_KEY:
        from_secret: CMS_API_KEY
    settings:
      create_repository: true
      enable_cache: true
      registry: 795250896452.dkr.ecr.us-east-1.amazonaws.com
      repo: devrel/${DRONE_REPO_NAME}
      build_args:
        - NPM_AUTH
        - NPM_EMAIL
        - CMS_URL
        - CMS_API_KEY
      tags:
        - educators-prod-build-${DRONE_BUILD_NUMBER}
        - latest-prod
      access_key:
        from_secret: ecr_access_key
      secret_key:
        from_secret: ecr_secret_key

trigger:
  branch:
    - production
  event:
    - push
  action:
    exclude:
      - synchronized

---
depends_on: null
kind: pipeline
type: kubernetes
name: deploy-educators-prod

steps:
  - name: deploy-prod
    image: quay.io/mongodb/drone-helm:v3
    settings:
      chart: mongodb/web-app
      chart_version: 4.7.3
      add_repos: [mongodb=https://10gen.github.io/helm-charts]
      namespace: devrel
      release: educators
      values: image.tag=educators-prod-build-${DRONE_BUILD_PARENT},image.pullPolicy=Always,image.repository=795250896452.dkr.ecr.us-east-1.amazonaws.com/devrel/${DRONE_REPO_NAME}
      api_server: https://api.prod.corp.mongodb.com
      kubernetes_token:
        from_secret: prod_kubernetes_token
      values_files: ['environments/prod.yaml']

trigger:
  event:
    - promote
    - rollback
  target:
    - production
