service:
  type: ClusterIP
  targetPort: 3000

env:
  APP_ENV: production

envSecrets:
  NPM_EMAIL: educators-secrets
  NPM_AUTH: educators-secrets
  CMS_URL: educators-secrets
  CMS_API_KEY: educators-secrets
  REVALIDATE_TOKEN: educators-secrets
  AIRTABLE_BASE_ID: educators-secrets
  AIRTABLE_API_KEY: educators-secrets
  REGISTRATION_API_URL: educators-secrets
  REGISTRATION_API_KEY: educators-secrets
  NEXT_PUBLIC_SENTRY_DSN: educators-secrets

autoscaling:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

probes:
  enabled: true
  path: /academia/api/health/
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

resources:
  limits:
    cpu: 2
    memory: 6Gi
  requests:
    cpu: 2
    memory: 6Gi

ingress:
  enabled: true
  path: /academia
  hosts: ['educators.devrel.prod.corp.mongodb.com']

prometheusRules:
  - alert: PodContainerNotReady
    expr: (sum(kube_pod_container_status_ready{container="educators",namespace="devrel"}) or vector(0)) == 0
    for: 1m
    labels:
      email_to: devhubplatform@mongodb.com
      severity: critical
    annotations:
      summary: "Container readiness check failed"
      description: "{{ $labels.instance }} of job {{ $labels.job }} container has not been ready for 1 minute"
