service:
  type: ClusterIP
  targetPort: 3000

env:
  IS_PROD: true

envSecrets:
  NPM_EMAIL: educators-secrets
  NPM_AUTH: educators-secrets
  AIRTABLE_BASE_ID: educators-secrets
  AIRTABLE_API_KEY: educators-secrets

autoscaling:
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

probes:
  enabled: true
  path: /academia/api/health/
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

resources:
  limits:
    cpu: 2
    memory: 6Gi
  requests:
    cpu: 2
    memory: 6Gi

ingress:
  enabled: true
  path: /academia
  hosts: ['educators.devrel.prod.corp.mongodb.com']
