service:
  type: ClusterIP
  targetPort: 3000

env:
  APP_ENV: staging

envSecrets:
  NPM_EMAIL: educators-secrets
  NPM_AUTH: educators-secrets
  CS_GRAPHQL_URL: educators-secrets
  CS_DELIVERY_TOKEN: educators-secrets
  REVALIDATE_TOKEN: educators-secrets
  NEXT_PUBLIC_SENTRY_DSN: educators-secrets
  NEXT_PUBLIC_SHEER_ID_KEY: educators-secrets
  SENTRY_AUTH_TOKEN: educators-secrets
  MONGODB_URL: educators-secrets
  AIRTABLE_BASE_ID: educators-secrets
  AIRTABLE_API_KEY: educators-secrets
  EDUCATOR_GOOGLE_DRIVE_FOLDER_ID: educators-secrets
  PHD_FELLOWSHIP_GOOGLE_DRIVE_FOLDER_ID: educators-secrets
  PHD_FELLOWSHIP_SPREADSHEET_ID: educators-secrets
  GOOGLE_DRIVE_PRIVATE_KEY: educators-secrets
  GOOGLE_DRIVE_CLIENT_EMAIL: educators-secrets

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

probes:
  enabled: true
  path: /academia/api/health/
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

ingress:
  enabled: true
  path: /academia
  hosts: ['educators.devrel.staging.corp.mongodb.com']

prometheusRules:
  - alert: PodContainerNotReady
    expr: (sum(kube_pod_container_status_ready{container="educators",namespace="devrel"}) or vector(0)) == 0
    for: 1m
    labels:
      email_to: devhubplatform@mongodb.com
      severity: critical
    annotations:
      summary: "Container readiness check failed"
      description: "{{ $labels.instance }} of job {{ $labels.job }} container has not been ready for 1 minute"
