service:
  type: ClusterIP
  targetPort: 3000

envSecrets:
  NPM_EMAIL: educators-secrets
  NPM_AUTH: educators-secrets
  CMS_URL: educators-secrets
  CMS_API_KEY: educators-secrets
  REVALIDATE_TOKEN: educators-secrets

autoscaling:
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80

probes:
  enabled: true
  path: /academia/api/health/
  headers: {}
  liveness:
    httpGet: true
    initialDelaySeconds: 10
    periodSeconds: 60
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3

resources:
  limits:
    cpu: 500m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 2Gi

ingress:
  enabled: true
  path: /academia
  hosts: ['educators.devrel.staging.corp.mongodb.com']

prometheusRules:
  - alert: PodContainerNotReady
    expr: kube_pod_container_status_ready{namespace="devrel", container="educators"} == 0
    for: 1m
    labels:
      email_to: devhubplatform@mongodb.com
      severity: critical
    annotations:
      summary: "Container readiness check failed"
      description: "{{ $labels.instance }} of job {{ $labels.job }} container has not been ready for 1 minute"
