name: Pull Request Checks
on:
  pull_request:
    branches: [main]
env:
  NPM_AUTH: ${{ secrets.NPM_AUTH }}
  NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
  CS_GRAPHQL_URL: ${{ secrets.CS_GRAPHQL_URL }}
  CS_DELIVERY_TOKEN: ${{ secrets.CS_DELIVERY_TOKEN }}
jobs:
  check-formatting-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run Prettier
        run: yarn pretty:check
      - name: Lint
        run: yarn lint
  jest-tests:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - name: Checkout target branch
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Run Jest tests with coverage report
        with:
          skip-step: install
        uses: ArtiomTr/jest-coverage-report-action@v2
